### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Victoria",
  "email": "test1@example.com",
  "password": "Password123!"
}

### Register another new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Michael",
  "email": "test2@example.com",
  "password": "Password123!"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test2@example.com",
  "password": "Password123!"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "Password123!"
}


### Submit a new AI tool
POST http://localhost:5000/tools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk
Content-Type: application/json

{
  "name": "ChatGPT",
  "description": "AI assistant for writing, research and coding",
  "category": "Productivity",
  "link": "https://chatgpt.com"
}

### Submit a new users AI tool
POST http://localhost:5000/tools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk
Content-Type: application/json

{
  "name": "MidJourney",
  "description": "AI assistant for writing, research and coding",
  "category": "Organisation",
  "link": "https://midjourney.com"
}

### Submit a new users AI tool
POST http://localhost:5000/tools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk
Content-Type: application/json

{
  "name": "Meta AI",
  "description": "AI assistant for writing, research and coding",
  "category": "Productivity",
  "link": "https://meta.ai"
}

### Submit another AI tool
POST http://localhost:5000/tools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyNWI0NDliYTI5Njc2ZDRiNTAiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTgzNzg2LCJleHAiOjE3ODcwNzAxODZ9.dQwbLMDZJIsIR1mhCKvv6s-rln1_SaBgkACrx-JJ8Fw
Content-Type: application/json

{
  "name": "Claude",
  "description": "AI assistant for writing, research and coding",
  "category": "Productivity",
  "link": "https://claude.ai"
}

### Submit another AI tool
POST http://localhost:5000/tools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk
Content-Type: application/json

{
  "name": "Grammarly",
  "description": "AI assistant for writing, research and coding",
  "category": "Writing",
  "link": "https://grammarly.com"
}

### Submit another AI tool
POST http://localhost:5000/tools
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyNWI0NDliYTI5Njc2ZDRiNTAiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTgzNzg2LCJleHAiOjE3ODcwNzAxODZ9.dQwbLMDZJIsIR1mhCKvv6s-rln1_SaBgkACrx-JJ8Fw
Content-Type: application/json

{
  "name": "Notion AI",
  "description": "AI assistant for writing, research and coding",
  "category": "Productivity",
  "link": "https://notion.ai"
}


### Upvote a tool
POST http://localhost:5000/tools/6a8344be6ecb1f05af5eb9d3/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk

### Upvote a tool
POST http://localhost:5000/tools/6a8344be6ecb1f05af5eb9d3/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyNWI0NDliYTI5Njc2ZDRiNTAiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTgzNzg2LCJleHAiOjE3ODcwNzAxODZ9.dQwbLMDZJIsIR1mhCKvv6s-rln1_SaBgkACrx-JJ8Fw

### Upvote a tool
POST http://localhost:5000/tools/6a8344bc6ecb1f05af5eb9d2/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk

### Upvote a tool
POST http://localhost:5000/tools/6a8344b76ecb1f05af5eb9d0/upvote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyZWI0NDliYTI5Njc2ZDRiNTEiLCJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTg0MjI2LCJleHAiOjE3ODcwNzA2MjZ9.-nWDXqhvFhpscP82rV-X2CBSWL2-B5zAzGaMu9tZaEk


### Delete a tool
DELETE http://localhost:5000/tools/6a8208030130965622ae5d96
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyNWI0NDliYTI5Njc2ZDRiNTAiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTgzNzg2LCJleHAiOjE3ODcwNzAxODZ9.dQwbLMDZJIsIR1mhCKvv6s-rln1_SaBgkACrx-JJ8Fw

### Get all tools
GET http://localhost:5000/tools

### Get popular tools
GET http://localhost:5000/tools/popular

### Get related tools
GET http://localhost:5000/tools/6a8344b76ecb1f05af5eb9d0/related


### Add comment to a tool
POST http://localhost:5000/tools/6a8344b76ecb1f05af5eb9d0/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyNWI0NDliYTI5Njc2ZDRiNTAiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTgzNzg2LCJleHAiOjE3ODcwNzAxODZ9.dQwbLMDZJIsIR1mhCKvv6s-rln1_SaBgkACrx-JJ8Fw
Content-Type: application/json

{
  "content": "I've been using this for coding and it's really helpful."
}

### Add another comment
POST http://localhost:5000/tools/6a8344b76ecb1f05af5eb9d0/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2YTgzMzUyNWI0NDliYTI5Njc2ZDRiNTAiLCJlbWFpbCI6InRlc3QxQGV4YW1wbGUuY29tIiwiaWF0IjoxNzg2OTgzNzg2LCJleHAiOjE3ODcwNzAxODZ9.dQwbLMDZJIsIR1mhCKvv6s-rln1_SaBgkACrx-JJ8Fw
Content-Type: application/json

{
  "content": "I especially like using this when I'm stuck on a difficult concept."
}

### Get all comments in a tool
GET http://localhost:5000/tools/6a8344b76ecb1f05af5eb9d0/comments


### Test server
GET http://localhost:5000/test